export type SocialPlatform = {
  id: string;
  name: string;
  icon: string;
  baseUrl: string;
  isCustom: boolean;
};

export const SOCIAL_PLATFORMS: SocialPlatform[] = [
  {
    id: "snapchat",
    name: "Snapchat",
    icon: "/socials/snapchat.svg",
    baseUrl: "snapchat.com/add/",
    isCustom: false,
  },
  {
    id: "youtube",
    name: "Youtube",
    icon: "/socials/youtube.svg",
    baseUrl: "youtube.com/",
    isCustom: false,
  },
  {
    id: "discord",
    name: "Discord",
    icon: "/socials/discord.svg",
    baseUrl: "discord.com/",
    isCustom: false,
  },
  {
    id: "peerlist",
    name: "Peerlist",
    icon: "/socials/peerlist.svg",
    baseUrl: "peerlist.com/",
    isCustom: false,
  },
  {
    id: "producthunt",
    name: "Product Hunt",
    icon: "/socials/producthunt.svg",
    baseUrl: "producthunt.com/",
    isCustom: false,
  },
  {
    id: "spotify",
    name: "Spotify",
    icon: "/socials/spotify.svg",
    baseUrl: "open.spotify.com/",
    isCustom: false,
  },
  {
    id: "instagram",
    name: "Instagram",
    icon: "/socials/instagram.svg",
    baseUrl: "instagram.com/",
    isCustom: false,
  },
  {
    id: "pinterest",
    name: "Pinterest",
    icon: "/socials/pinterest.svg",
    baseUrl: "pinterest.com/",
    isCustom: false,
  },
  {
    id: "twitter",
    name: "Twitter",
    icon: "/socials/twitter.svg",
    baseUrl: "x.com/",
    isCustom: false,
  },
  {
    id: "tiktok",
    name: "TikTok",
    icon: "/socials/tiktok.svg",
    baseUrl: "tiktok.com/",
    isCustom: false,
  },
  {
    id: "telegram",
    name: "Telegram",
    icon: "/socials/telegram.svg",
    baseUrl: "t.me/",
    isCustom: false,
  },
  {
    id: "substack",
    name: "Substack",
    icon: "/socials/substack.svg",
    baseUrl: "substack.com/",
    isCustom: false,
  },
  {
    id: "soundcloud",
    name: "Soundcloud",
    icon: "/socials/soundcloud.svg",
    baseUrl: "soundcloud.com/",
    isCustom: false,
  },
  {
    id: "paypal",
    name: "PayPal",
    icon: "/socials/paypal.svg",
    baseUrl: "paypal.me/",
    isCustom: false,
  },
  {
    id: "github",
    name: "Github",
    icon: "/socials/github.svg",
    baseUrl: "github.com/",
    isCustom: false,
  },
  {
    id: "slack",
    name: "Slack",
    icon: "/socials/slack.svg",
    baseUrl: "",
    isCustom: false,
  },
  {
    id: "apple-music",
    name: "Apple Music",
    icon: "/socials/apple-music.svg",
    baseUrl: "music.apple.com/",
    isCustom: false,
  },
  {
    id: "gitlab",
    name: "GitLab",
    icon: "/socials/gitlab.svg",
    baseUrl: "gitlab.com/",
    isCustom: false,
  },
  {
    id: "twitch",
    name: "Twitch",
    icon: "/socials/twitch.svg",
    baseUrl: "twitch.tv/",
    isCustom: false,
  },
  {
    id: "leetcode",
    name: "Leetcode",
    icon: "/socials/leetcode.svg",
    baseUrl: "leetcode.com/u/",
    isCustom: false,
  },
  {
    id: "reddit",
    name: "Reddit",
    icon: "/socials/reddit.svg",
    baseUrl: "reddit.com/",
    isCustom: false,
  },
  {
    id: "vk",
    name: "VK",
    icon: "/socials/vk.svg",
    baseUrl: "vk.com/",
    isCustom: false,
  },
  {
    id: "namemc",
    name: "NameMC",
    icon: "/socials/namemc.svg",
    baseUrl: "namemc.com/",
    isCustom: false,
  },
  {
    id: "linkedin",
    name: "LinkedIn",
    icon: "/socials/linkedin.svg",
    baseUrl: "linkedin.com/",
    isCustom: false,
  },
  {
    id: "hackerrank",
    name: "HackerRank",
    icon: "/socials/hackerrank.svg",
    baseUrl: "hackerrank.com/profile/",
    isCustom: false,
  },
  {
    id: "steam",
    name: "Steam",
    icon: "/socials/steam.svg",
    baseUrl: "steamcommunity.com/id/",
    isCustom: false,
  },
  {
    id: "kick",
    name: "Kick",
    icon: "/socials/kick.svg",
    baseUrl: "kick.com/",
    isCustom: false,
  },
  {
    id: "pinterest",
    name: "Pinterest",
    icon: "/socials/pinterest.svg",
    baseUrl: "pinterest.com/",
    isCustom: false,
  },
  {
    id: "buy-me-a-coffee",
    name: "Buy Me A Coffee",
    icon: "/socials/bmc.svg",
    baseUrl: "buymeacoffee.com/",
    isCustom: false,
  },
  {
    id: "facebook",
    name: "Facebook",
    icon: "/socials/facebook.svg",
    baseUrl: "facebook.com/",
    isCustom: false,
  },
  {
    id: "gumroad",
    name: "Gumroad",
    icon: "/socials/gumroad.svg",
    baseUrl: "gumroad.com/",
    isCustom: false,
  },
  {
    id: "email",
    name: "Email",
    icon: "/socials/gmail.svg",
    baseUrl: "mailto:",
    isCustom: false,
  },
  {
    id: "whatsapp",
    name: "Whatsapp",
    icon: "/socials/whatsapp.svg",
    baseUrl: "wa.me/",
    isCustom: false,
  },
  {
    id: "appstore",
    name: "App Store",
    icon: "/socials/appstore.svg",
    baseUrl: "apps.apple.com/developer/",
    isCustom: false,
  },
  {
    id: "bluesky",
    name: "Blue Sky",
    icon: "/socials/bluesky.svg",
    baseUrl: "bsky.app/profile/",
    isCustom: false,
  },
  {
    id: "codeforces",
    name: "Code Forces",
    icon: "/socials/codeforces.svg",
    baseUrl: "codeforces.com/profile/",
    isCustom: false,
  },
  {
    id: "dailydev",
    name: "Daily Dev",
    icon: "/socials/dailydev.svg",
    baseUrl: "app.daily.dev/",
    isCustom: false,
  },
  {
    id: "dribbble",
    name: "Dribbble",
    icon: "/socials/dribbble.svg",
    baseUrl: "dribbble.com/",
    isCustom: false,
  },
  {
    id: "google-play",
    name: "Google Play Store",
    icon: "/socials/googleplay.svg",
    baseUrl: "play.google.com/store/apps/dev?id=",
    isCustom: false,
  },
  {
    id: "hashnode",
    name: "Hashnode",
    icon: "/socials/hashnode.svg",
    baseUrl: "hashnode.com/",
    isCustom: false,
  },
  {
    id: "modrinth",
    name: "Modrinth",
    icon: "/socials/modrinth.svg",
    baseUrl: "modrinth.com/user/",
    isCustom: false,
  },
];
